services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch_ir_project
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node

      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

      - ES_JAVA_OPTS=-Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - es_data:/usr/share/elasticsearch/data

    networks:
      - ir_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana_ir_project
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none

    ports:
      - "5601:5601"

    depends_on:
      - elasticsearch

    networks:
      - ir_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_ir_project
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=recipe_db

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

    networks:
      - ir_network

  adminer:
    image: adminer
    container_name: adminer_ir_project

    ports:
      - "8080:8080"

    depends_on:
      - postgres

    networks:
      - ir_network

networks:
  ir_network:
    driver: bridge

volumes:
  es_data:
  pg_data: